server: 
    port: 8086

spring:
    datasource:
        name: test
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/metrorailwaymanagementsystem?useUnicode=true&characterEncoding=utf8
        username: root
        password: zxlhlm@@

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.demo.entity